const Listdata = [
          {
                    id: 1,
                    title: "A Great Apartment Next to the Beach!",
                    img: "https://images.pexels.com/photos/1918291/pexels-photo-1918291.jpeg",
                    bedRooms: 2,
                    bathRooms: 1,
                    price: 1000,
                    address: "456 Park Avenue, London",
                    latitude: 51.5074,
                    longitude: -0.1278,
          },
          {
                    id: 2,
                    title: "An Awesome Apartment Near the Park! Almost too good to be true!",
                    img: "https://images.pexels.com/photos/1428348/pexels-photo-1428348.jpeg",
                    bedRooms: 3,
                    bathRooms: 2,
                    price: 1500,
                    address: "789 Oxford Street, London",
                    latitude: 52.4862,
                    longitude: -1.8904,
          },
          {
                    id: 3,
                    title: "Modern Apartment With City View",
                    img: "https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg",
                    bedRooms: 2,
                    bathRooms: 1,
                    price: 1200,
                    address: "12 High Street, Manchester",
                    latitude: 53.4808,
                    longitude: -2.2426,
          },
          {
                    id: 4,
                    title: "Cozy Studio in the City Center",
                    img: "https://images.pexels.com/photos/1454806/pexels-photo-1454806.jpeg",
                    bedRooms: 1,
                    bathRooms: 1,
                    price: 800,
                    address: "22 King Street, Birmingham",
                    latitude: 52.4862,
                    longitude: -1.8904,
          },
          {
                    id: 5,
                    title: "Spacious Family Home With Garden",
                    img: "https://images.pexels.com/photos/106399/pexels-photo-106399.jpeg",
                    bedRooms: 4,
                    bathRooms: 2,
                    price: 1800,
                    address: "34 Green Lane, Leeds",
                    latitude: 53.8008,
                    longitude: -1.5491,
          },
          {
                    id: 6,
                    title: "Stylish Apartment Close to the River",
                    img: "https://images.pexels.com/photos/4392270/pexels-photo-4392270.jpeg",
                    bedRooms: 2,
                    bathRooms: 2,
                    price: 1400,
                    address: "56 Riverside Road, Bristol",
                    latitude: 51.4545,
                    longitude: -2.5879,
          },
          {
                    id: 7,
                    title: "Penthouse With Rooftop Terrace",
                    img: "https://images.pexels.com/photos/439391/pexels-photo-439391.jpeg",
                    bedRooms: 3,
                    bathRooms: 2,
                    price: 2300,
                    address: "78 Skyline Avenue, London",
                    latitude: 51.5155,
                    longitude: -0.1410,
          },
          {
                    id: 8,
                    title: "Student-Friendly Flat Near University",
                    img: "https://images.pexels.com/photos/271639/pexels-photo-271639.jpeg",
                    bedRooms: 3,
                    bathRooms: 1,
                    price: 1100,
                    address: "90 Campus Road, Nottingham",
                    latitude: 52.9548,
                    longitude: -1.1581,
          },
          {
                    id: 9,
                    title: "Minimalist Studio for Young Professionals",
                    img: "https://images.pexels.com/photos/37347/office-room-workspace-coworking.jpeg",
                    bedRooms: 1,
                    bathRooms: 1,
                    price: 950,
                    address: "101 George Square, Glasgow",
                    latitude: 55.8642,
                    longitude: -4.2518,
          },
          {
                    id: 10,
                    title: "Large House Perfect for Families",
                    img: "https://images.pexels.com/photos/259588/pexels-photo-259588.jpeg",
                    bedRooms: 5,
                    bathRooms: 3,
                    price: 2100,
                    address: "120 Dockside Street, Liverpool",
                    latitude: 53.4084,
                    longitude: -2.9916,
          },
          {
                    id: 11,
                    title: "Duplex Apartment With Home Office",
                    img: "https://images.pexels.com/photos/2102587/pexels-photo-2102587.jpeg",
                    bedRooms: 3,
                    bathRooms: 2,
                    price: 1700,
                    address: "135 Castle Hill, Edinburgh",
                    latitude: 55.9533,
                    longitude: -3.1883,
          },
          {
                    id: 12,
                    title: "Cozy Cottage-Style Flat",
                    img: "https://images.pexels.com/photos/2716398/pexels-photo-2716398.jpeg",
                    bedRooms: 2,
                    bathRooms: 1,
                    price: 1050,
                    address: "150 Bay Street, Cardiff",
                    latitude: 51.4816,
                    longitude: -3.1791,
          },
];

export default Listdata;


