const Listdata = [
          {
                    id: 1,
                    title: "A Great Apartment Next to the Beach!",
                    img: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750",
                    bedRooms: 2,
                    bathRooms: 1,
                    price: 1000,
                    address: "456 Park Avenue, London",
                    latitude: 51.5074,
                    longitude: -0.1278,
          },
          {
                    id: 2,
                    title: "An Awesome Apartment Near the Park! Almost too good to be true!",
                    img: "https://images.unsplash.com/photo-1570129477492-45c003edd2be",
                    bedRooms: 3,
                    bathRooms: 2,
                    price: 1500,
                    address: "789 Oxford Street, London",
                    latitude: 52.4862,
                    longitude: -1.8904,
          },
          {
                    id: 3,
                    title: "Modern Apartment With City View",
                    img: "https://images.unsplash.com/photo-1527030280862-64139fba04ca",
                    bedRooms: 2,
                    bathRooms: 1,
                    price: 1200,
                    address: "12 High Street, Manchester",
                    latitude: 53.4808,
                    longitude: -2.2426,
          },
          {
                    id: 4,
                    title: "Cozy Studio in the City Center",
                    img: "https://images.unsplash.com/photo-1507089947368-19c1da9775ae",
                    bedRooms: 1,
                    bathRooms: 1,
                    price: 800,
                    address: "22 King Street, Birmingham",
                    latitude: 52.4862,
                    longitude: -1.8904,
          },
          {
                    id: 5,
                    title: "Spacious Family Home With Garden",
                    img: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2",
                    bedRooms: 4,
                    bathRooms: 2,
                    price: 1800,
                    address: "34 Green Lane, Leeds",
                    latitude: 53.8008,
                    longitude: -1.5491,
          },
          {
                    id: 6,
                    title: "Stylish Apartment Close to the River",
                    img: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267",
                    bedRooms: 2,
                    bathRooms: 2,
                    price: 1400,
                    address: "56 Riverside Road, Bristol",
                    latitude: 51.4545,
                    longitude: -2.5879,
          },
          {
                    id: 7,
                    title: "Penthouse With Rooftop Terrace",
                    img: "https://images.unsplash.com/photo-1502673530728-f79b4cab31b1",
                    bedRooms: 3,
                    bathRooms: 2,
                    price: 2300,
                    address: "78 Skyline Avenue, London",
                    latitude: 51.5155,
                    longitude: -0.1410,
          },
          {
                    id: 8,
                    title: "Student-Friendly Flat Near University",
                    img: "https://images.unsplash.com/photo-1523217582562-09d0def993a6",
                    bedRooms: 3,
                    bathRooms: 1,
                    price: 1100,
                    address: "90 Campus Road, Nottingham",
                    latitude: 52.9548,
                    longitude: -1.1581,
          },
          {
                    id: 9,
                    title: "Minimalist Studio for Young Professionals",
                    img: "https://images.unsplash.com/photo-1519710164239-da123dc03ef4",
                    bedRooms: 1,
                    bathRooms: 1,
                    price: 950,
                    address: "101 George Square, Glasgow",
                    latitude: 55.8642,
                    longitude: -4.2518,
          },
          {
                    id: 10,
                    title: "Large House Perfect for Families",
                    img: "https://images.unsplash.com/photo-1598928506311-c55ded1f1387",
                    bedRooms: 5,
                    bathRooms: 3,
                    price: 2100,
                    address: "120 Dockside Street, Liverpool",
                    latitude: 53.4084,
                    longitude: -2.9916,
          },
          {
                    id: 11,
                    title: "Duplex Apartment With Home Office",
                    img: "https://images.unsplash.com/photo-1502672023488-70e25813eb80",
                    bedRooms: 3,
                    bathRooms: 2,
                    price: 1700,
                    address: "135 Castle Hill, Edinburgh",
                    latitude: 55.9533,
                    longitude: -3.1883,
          },
          {
                    id: 12,
                    title: "Cozy Cottage-Style Flat",
                    img: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c",
                    bedRooms: 2,
                    bathRooms: 1,
                    price: 1050,
                    address: "150 Bay Street, Cardiff",
                    latitude: 51.4816,
                    longitude: -3.1791,
          },
];

export default Listdata;
